main: de.rangun.pangaeablocks.PangaeaBlocksPlugin
name: PangaeaBlocks
author: Velnias75
website: https://discord.gg/kQP9QSG6F4
version: '@version@'
api-version: '1.18'
commands:
  lockdoor:
    description: locks resp. protects a door/gate/trapdoor
    permission: pangaeablocks.lockdoor
    usage: /lockdoor
  unlockdoor:
    description: unlocks resp. unprotects a door/gate/trapdoor
    permission: pangaeablocks.lockdoor
    usage: /unlockdoor
