main: de.rangun.pangaeablocks.PangaeaBlocksPlugin
name: PangaeaBlocks
author: Velnias75
website: https://discord.gg/tkX9BcwCCS
version: '@version@'
api-version: '1.19'
softdepend: [DiscordSRV, LuckPerms]
depend: [PinkBull]
permissions:
  pangaeablocks.invsee_blocked:
    default: false
  pangaeablocks.welcome_new_players:
    default: op
  pangaeablocks.taxi.give:
    default: op
commands:
  lockdoor:
    description: locks resp. protects a door/gate/trapdoor
    permission: pangaeablocks.lockdoor
    usage: /lockdoor
  unlockdoor:
    description: unlocks resp. unprotects a door/gate/trapdoor
    permission: pangaeablocks.lockdoor
    usage: /unlockdoor
  hologram:
    description: turns an armor stand into a hologram
    permission: pangaeablocks.hologram
    usage: /hologram [text]
  frame:
    description: toggles frame attributes
    permission: pangaeablocks.frame
    usage: /frame (toggle_visibility|toggle_fixation)
  ticket:
    description: tbw
    permission: pangaeablocks.ticket
    usage: /ticket
  pvp:
    description: enable/disable PvP
    permission: pangaeablocks.pvp
    usage: /pvp [on|off]
  invsee:
    description: tbw
    permission: pangaeablocks.invsee
    usage: /invsee [player]
  taxi:
    description: tbw
    permission: pangaeablocks.taxi
    usage: /taxi